//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRestAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_tab
    {
        public decimal employee_id { get; set; }
        public string name { get; set; }
        public string designation { get; set; }
        public string city { get; set; }
        public decimal basic { get; set; }
        public string qualification { get; set; }
    }
}
