//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRestAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public decimal sno { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public decimal did { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
