//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRestAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplymaster
    {
        public double sno { get; set; }
        public string Custcode { get; set; }
        public string partno { get; set; }
        public string supplymonth { get; set; }
        public string Module { get; set; }
        public string productcode { get; set; }
        public Nullable<double> custgroup { get; set; }
        public Nullable<double> qty { get; set; }
        public Nullable<double> recordtype { get; set; }
        public Nullable<double> cost { get; set; }
    }
}
